### ISSUE TITLE
"View project" just scrolls up

### ISSUE THREAD

**Issue by IonicaBizau** [carolinaknoll/carolinaknoll.github.io#1]
When clicking the <kbd>View project</kbd> buttons, the page scrolls up. I guess that should open the project page/view. 💭 

Nice stuff here! Keep up the good work, @carolinaknoll! ✨

**Comment by carolinaknoll** [comment]
This is happening because most of my projects aren't published yet. As they are really simple, I plan to publish them via GitHub Pages. When I do that I will update the anchor tags to point to each project page correctly and this issue will be fixed. :thought_balloon:

Thanks a lot for pointing it out, @IonicaBizau! :sparkles:

**Comment by IonicaBizau** [comment]
@carolinaknoll Nice, you can leave updates in this issue while you're adding them. I'm curious. 😁

**Comment by carolinaknoll** [comment]
Portfolio is now updated with the correct links to the project pages. You're able to check them [here](http://carolinaknoll.github.io/#portfolio). :memo:

Thank you, @IonicaBizau! :smile:

**Comment by IonicaBizau** [comment]
@carolinaknoll Nice stuff! ✨ ❇️ 😃
